-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.agendamento
(
    id integer NOT NULL DEFAULT nextval('agendamento_id_seq'::regclass),
    id_client integer NOT NULL DEFAULT nextval('agendamento_id_client_seq'::regclass),
    id_funcio integer NOT NULL DEFAULT nextval('agendamento_id_funcio_seq'::regclass),
    hour time without time zone,
    user_type_id integer,
    CONSTRAINT agendamento_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.horario
(
    id integer NOT NULL DEFAULT nextval('horario_id_seq'::regclass),
    data date NOT NULL,
    hour_ini time without time zone NOT NULL,
    hour_final time without time zone NOT NULL,
    CONSTRAINT horario_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.service
(
    id integer NOT NULL DEFAULT nextval('service_id_seq'::regclass),
    service character varying COLLATE pg_catalog."default" NOT NULL,
    price money,
    CONSTRAINT service_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.user_type
(
    id integer NOT NULL DEFAULT nextval('user_type_id_seq'::regclass),
    type character varying COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT user_type_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.users
(
    id integer NOT NULL DEFAULT nextval('users_id_seq'::regclass),
    name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    email character varying(255) COLLATE pg_catalog."default" NOT NULL,
    phone integer,
    password character varying(255) COLLATE pg_catalog."default",
    user_type_id integer NOT NULL DEFAULT nextval('users_user_type_id_seq'::regclass),
    CONSTRAINT users_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.users_service
(
    id integer NOT NULL DEFAULT nextval('users_service_id_seq'::regclass),
    users_id integer NOT NULL,
    service_id integer NOT NULL,
    CONSTRAINT users_service_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.agendamento
    ADD CONSTRAINT user_type_id FOREIGN KEY (user_type_id)
    REFERENCES public.user_type (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.users
    ADD CONSTRAINT user_type_id FOREIGN KEY (user_type_id)
    REFERENCES public.user_type (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.users_service
    ADD CONSTRAINT service_id FOREIGN KEY (service_id)
    REFERENCES public.service (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.users_service
    ADD CONSTRAINT users_id FOREIGN KEY (users_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;